[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = [
  "solmate/=lib/solmate/src/",
  "forge-std/=lib/forge-std/src/",
  "@opensezppling/=lib/openzeppelin-contracts/",
  "@scroll-tech/contracts@0.1.0/=node_modules/@scroll-tech/contracts/"
]
verbosity = 1
evm_version = "london"

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4
